markdown: rdiscount
permalink: /:title.html
paginate: 5
highlighter: rouge
url : "http://huxiangtao.github.com"
name: "elliot's blog"
encoding: utf-8
version : "?201403267"
gems: [jekyll,jekyll-paginate]
