markdown: kramdown
kramdown:
  input:  GFM
  use_coderay: true
  coderay_tab_width: 2
  extensions: [ "fenced_code_blocks", "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]
  syntax_highlighter: rouge
  coderay:
    coderay_line_numbers:  nil
permalink: /:title.html
paginate: 5
highlighter: rouge
url : "http://huxiangtao.github.com"
name: "elliot's blog"
encoding: utf-8
version : "?201403267"
gems: [jekyll,jekyll-paginate]
description: ["developer","researcher","bloger"]
